//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteIntoFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasteIntoFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Into File.
        /// </summary>
        internal static string explorer_context_entry {
            get {
                return ResourceManager.GetString("explorer_context_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ….
        /// </summary>
        internal static string str_ellipsis {
            get {
                return ResourceManager.GetString("str_ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string str_extension {
            get {
                return ResourceManager.GetString("str_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved :).
        /// </summary>
        internal static string str_file_saved {
            get {
                return ResourceManager.GetString("str_file_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string str_filename {
            get {
                return ResourceManager.GetString("str_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        internal static string str_location {
            get {
                return ResourceManager.GetString("str_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you are running this application for the first time,
        ///do you want to add an entry to the explorer context menu?.
        /// </summary>
        internal static string str_message_first_time {
            get {
                return ResourceManager.GetString("str_message_first_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Into File helps you paste any text or images in your system clipboard into a file directly instead of creating new file yourself
        ///      
        ///--------------------
        ///      
        ///To Register the application to your system context menu run the program as administrator with this argument : /reg
        ///to Unregister the application use this argument : /unreg
        ///To change the format of the default filename, use this argument: /filename yyyy-MM-dd_HHmm
        ///
        ///--------------------
        ///
        ///https://github.com/EslaMx7/PasteIntoFile
        ///Send [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string str_message_help {
            get {
                return ResourceManager.GetString("str_message_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer context menu entry has been added.
        /// </summary>
        internal static string str_message_register_context_menu_success {
            get {
                return ResourceManager.GetString("str_message_register_context_menu_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename-template has been registered.
        /// </summary>
        internal static string str_message_register_filename_success {
            get {
                return ResourceManager.GetString("str_message_register_filename_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the application as Administrator!.
        /// </summary>
        internal static string str_message_run_as_admin {
            get {
                return ResourceManager.GetString("str_message_run_as_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer context menu entry has been removed.
        /// </summary>
        internal static string str_message_unregister_context_menu_success {
            get {
                return ResourceManager.GetString("str_message_unregister_context_menu_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string str_save {
            get {
                return ResourceManager.GetString("str_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder for saving this file .
        /// </summary>
        internal static string str_select_folder {
            get {
                return ResourceManager.GetString("str_select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file.
        /// </summary>
        internal static string str_type_img {
            get {
                return ResourceManager.GetString("str_type_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        internal static string str_type_txt {
            get {
                return ResourceManager.GetString("str_type_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file.
        /// </summary>
        internal static string str_type_unknown {
            get {
                return ResourceManager.GetString("str_type_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Into File.
        /// </summary>
        internal static string window_title {
            get {
                return ResourceManager.GetString("window_title", resourceCulture);
            }
        }
    }
}
